# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "reelkart-new"
client_id = "8b45137628093f04ee947f94f32e8c76"
application_url = "https://77b5-192-140-153-61.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://77b5-192-140-153-61.ngrok-free.app/auth/callback",
  "https://77b5-192-140-153-61.ngrok-free.app/auth/shopify/callback",
  "https://77b5-192-140-153-61.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "reelkart-test-v1.myshopify.com"
